// ============================================================================
// Built-in demo data. Used automatically whenever Supabase is NOT configured,
// so you can build and view the whole app before creating any account.
// Mirrors db/seed.sql.
// ============================================================================
import type { Product, Shop } from "./types";

const now = () => new Date().toISOString();

const seedShops: Shop[] = [
  {
    id: "shop-zara",
    address: "Shop 14, Tariq Road, Karachi",
    deliveryZones: [{ city: "Karachi", fee: 0 }, { city: "Lahore", fee: 250 }],
    themeColor: "#8E2C5A",
    bannerStyle: "color",
    bannerImage: null,
    bannerHeading: "Eid Edit — new arrivals",
    bannerSubtext: "Lawn, formals & more. Cash on Delivery all over Pakistan.",
    slug: "zara",
    name: "Zara Boutique",
    tagline: "Online · replies fast",
    industry: "Fashion",
    logoText: "ZB",
    logoUrl: null,
    aboutText:
      "Zara Boutique started in 2021 from a small home setup in Lahore. We hand-pick lawn, formals and accessories from trusted makers, check every piece ourselves, and ship all over Pakistan with Cash on Delivery. Thousands of happy customers later, we still reply to every message personally.",
    returnPolicy: "7day",
    returnPolicyNote: "Sale items can be exchanged for a different size, but not refunded.",
    whatsapp: "923001234567",
    paymentNote: "JazzCash / Easypaisa: 0300 1234567 (title: Zara Boutique)",
    freeDeliveryOver: 3000,
    deliveryFee: 200,
    currency: "PKR",
    verificationStatus: "verified",
    cnicNumber: null,
    cnicImageUrl: null,
    selfieImageUrl: null,
    payoutMethod: "easypaisa",
    payoutAccountName: "Zara Boutique",
    payoutAccountNumber: "03001234567",
    verificationSubmittedAt: now(),
    verificationReviewedAt: now(),
    verificationNote: null,
    instagramUrl: null,
    facebookUrl: null,
    tiktokUrl: null,
    youtubeUrl: null,
    signupSource: null,
    promoCode: null,
    referredByShop: null,
    referrerRewarded: false,
    featured: false,
    fbPixelId: null,
    gaMeasurementId: null,
    seoTitle: null,
    seoDescription: null,
    referralAmount: 150,
    salePercent: null,
    saleEndsAt: null,
    template: "classic",
    plan: "pro",
    trialEndsAt: null,
    subscriptionStatus: "active",
    planExpiresAt: null,
    isActive: true,
    createdAt: now(),
  },
  {
    id: "shop-hina",
    address: null,
    deliveryZones: [],
    themeColor: "#0E6E62",
    bannerStyle: "none",
    bannerImage: null,
    bannerHeading: null,
    bannerSubtext: null,
    slug: "hina",
    name: "Hina's Closet",
    tagline: "Abayas & hijabs",
    industry: "Fashion",
    logoText: "HC",
    logoUrl: null,
    aboutText: null,
    returnPolicy: null,
    returnPolicyNote: null,
    whatsapp: "923012223344",
    paymentNote: "Easypaisa: 0301 2223344 (Hina)",
    freeDeliveryOver: 4000,
    deliveryFee: 150,
    currency: "PKR",
    verificationStatus: "pending",
    cnicNumber: "4210112345678",
    cnicImageUrl: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSc2NDAnIGhlaWdodD0nNDAwJz48cmVjdCB3aWR0aD0nNjQwJyBoZWlnaHQ9JzQwMCcgcng9JzE4JyBmaWxsPScjZGZlN2VlJy8+PHJlY3QgeD0nMzAnIHk9JzMwJyB3aWR0aD0nMTYwJyBoZWlnaHQ9JzIwMCcgcng9JzEwJyBmaWxsPScjOWZiM2M4Jy8+PGNpcmNsZSBjeD0nMTEwJyBjeT0nMTEwJyByPSc1NScgZmlsbD0nIzZiN2Y5NicvPjxyZWN0IHg9JzU1JyB5PScxODAnIHdpZHRoPScxMTAnIGhlaWdodD0nNDAnIHJ4PSc4JyBmaWxsPScjNmI3Zjk2Jy8+PHRleHQgeD0nMjMwJyB5PSc3MCcgZm9udC1mYW1pbHk9J3NhbnMtc2VyaWYnIGZvbnQtc2l6ZT0nMjgnIGZpbGw9JyMxZjJkM2EnPlBha2lzdGFuIOKAlCBDTklDPC90ZXh0Pjx0ZXh0IHg9JzIzMCcgeT0nMTMwJyBmb250LWZhbWlseT0nc2Fucy1zZXJpZicgZm9udC1zaXplPScyMicgZmlsbD0nIzMzNDc1Yic+SGluYSBSYXphPC90ZXh0Pjx0ZXh0IHg9JzIzMCcgeT0nMTc1JyBmb250LWZhbWlseT0nbW9ub3NwYWNlJyBmb250LXNpemU9JzIyJyBmaWxsPScjMzM0NzViJz40MjEwMS0xMjM0NTY3LTg8L3RleHQ+PC9zdmc+",
    selfieImageUrl: "data:image/svg+xml;base64,PHN2ZyB4bWxucz0naHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmcnIHdpZHRoPSc0ODAnIGhlaWdodD0nNDgwJz48cmVjdCB3aWR0aD0nNDgwJyBoZWlnaHQ9JzQ4MCcgZmlsbD0nI2VlZjFlZScvPjxjaXJjbGUgY3g9JzI0MCcgY3k9JzIwMCcgcj0nOTUnIGZpbGw9JyM2YjdmOTYnLz48cmVjdCB4PScxMjAnIHk9JzMwMCcgd2lkdGg9JzI0MCcgaGVpZ2h0PScxNTAnIHJ4PSc4MCcgZmlsbD0nIzZiN2Y5NicvPjx0ZXh0IHg9JzI0MCcgeT0nNDU1JyBmb250LWZhbWlseT0nc2Fucy1zZXJpZicgZm9udC1zaXplPScyNicgdGV4dC1hbmNob3I9J21pZGRsZScgZmlsbD0nIzMzNDc1Yic+U2VsZmllPC90ZXh0Pjwvc3ZnPg==",
    payoutMethod: "jazzcash",
    payoutAccountName: "Hina Raza",
    payoutAccountNumber: "03007654321",
    verificationSubmittedAt: now(),
    verificationReviewedAt: null,
    verificationNote: null,
    instagramUrl: "instagram.com/hina.styles",
    facebookUrl: null,
    tiktokUrl: null,
    youtubeUrl: null,
    signupSource: null,
    promoCode: null,
    referredByShop: null,
    referrerRewarded: false,
    featured: false,
    fbPixelId: null,
    gaMeasurementId: null,
    seoTitle: null,
    seoDescription: null,
    referralAmount: null,
    salePercent: null,
    saleEndsAt: null,
    template: "classic",
    plan: "basic",
    trialEndsAt: null,
    subscriptionStatus: "active",
    planExpiresAt: null,
    isActive: true,
    createdAt: now(),
  },
  {
    id: "shop-bilal",
    address: null,
    deliveryZones: [],
    themeColor: "#2F4A8A",
    bannerStyle: "none",
    bannerImage: null,
    bannerHeading: null,
    bannerSubtext: null,
    slug: "bilal-tech",
    name: "Bilal Electronics",
    tagline: "Gadgets & accessories",
    industry: "Electronics",
    logoText: "BE",
    logoUrl: null,
    aboutText: null,
    returnPolicy: null,
    returnPolicyNote: null,
    whatsapp: "923023334455",
    paymentNote: "Bank transfer on request",
    freeDeliveryOver: null,
    deliveryFee: 250,
    currency: "PKR",
    verificationStatus: "unverified",
    cnicNumber: null,
    cnicImageUrl: null,
    selfieImageUrl: null,
    payoutMethod: null,
    payoutAccountName: null,
    payoutAccountNumber: null,
    verificationSubmittedAt: null,
    verificationReviewedAt: null,
    verificationNote: null,
    instagramUrl: null,
    facebookUrl: null,
    tiktokUrl: null,
    youtubeUrl: null,
    signupSource: null,
    promoCode: null,
    referredByShop: null,
    referrerRewarded: false,
    featured: false,
    fbPixelId: null,
    gaMeasurementId: null,
    seoTitle: null,
    seoDescription: null,
    referralAmount: null,
    salePercent: null,
    saleEndsAt: null,
    template: "classic",
    plan: "trial",
    // Demo: trial ending soon with zero products — appears on the admin At-risk radar.
    trialEndsAt: new Date(Date.now() + 2 * 86400000).toISOString(),
    subscriptionStatus: "active",
    planExpiresAt: null,
    isActive: true,
    createdAt: now(),
  },
  {
    id: "shop-old",
    address: null,
    deliveryZones: [],
    themeColor: null,
    bannerStyle: "none",
    bannerImage: null,
    bannerHeading: null,
    bannerSubtext: null,
    slug: "old-boutique",
    name: "Old Boutique",
    tagline: null,
    industry: "Retail",
    logoText: "OB",
    logoUrl: null,
    aboutText: null,
    returnPolicy: null,
    returnPolicyNote: null,
    whatsapp: "923034445566",
    paymentNote: null,
    freeDeliveryOver: null,
    deliveryFee: 200,
    currency: "PKR",
    verificationStatus: "unverified",
    cnicNumber: null,
    cnicImageUrl: null,
    selfieImageUrl: null,
    payoutMethod: null,
    payoutAccountName: null,
    payoutAccountNumber: null,
    verificationSubmittedAt: null,
    verificationReviewedAt: null,
    verificationNote: null,
    instagramUrl: null,
    facebookUrl: null,
    tiktokUrl: null,
    youtubeUrl: null,
    signupSource: null,
    promoCode: null,
    referredByShop: null,
    referrerRewarded: false,
    featured: false,
    fbPixelId: null,
    gaMeasurementId: null,
    seoTitle: null,
    seoDescription: null,
    referralAmount: null,
    salePercent: null,
    saleEndsAt: null,
    template: "classic",
    plan: "basic",
    trialEndsAt: null,
    subscriptionStatus: "active",
    // Demo: paid plan expiring in 4 days — appears on the Revenue renewal chase list.
    planExpiresAt: new Date(Date.now() + 4 * 86400000).toISOString(),
    isActive: false,
    createdAt: now(),
  },
];

const seedProducts: Product[] = [
  {
    id: "p-lawn",
    options: [],
    tag: "bestseller",
    shopId: "shop-zara",
    name: "Lawn Suit (3pc)",
    description:
      "Unstitched premium lawn, 3 pieces. Soft, breathable and summer-ready. Dupatta included.",
    longDescription:
      "<p><b>Fabric:</b> premium summer lawn — light, soft and breathable, so it stays comfortable even in June heat.</p>" +
      "<p><b>What you get:</b> shirt, trouser and dupatta. Unstitched, so your darzi can fit it to you exactly.</p>" +
      "<p><b>Care:</b> hand wash cold, dry in shade, iron on medium. The colours stay bright for years.</p>" +
      "<p><b>Why we love it:</b> the print is block-printed by hand, so no two suits are exactly the same.</p>",
    price: 4500,
    compareAtPrice: 5500,
  costPrice: 3100,
  videoUrl: null,
  sizeChartUrl: null,
  dropAt: null,
    stock: 12,
    category: "Dresses",
    imageUrls: [],
    isActive: true,
    createdAt: now(),
  },
  {
    id: "p-kurti",
    options: [{ name: "Size", values: ["S", "M", "L"] }, { name: "Colour", values: ["Black", "Maroon"] }],
    tag: "hot",
    shopId: "shop-zara",
    name: "Embroidered Kurti",
    description: "Hand-embroidered cotton kurti with detailed neckline work.",
    longDescription: null,
    price: 2200,
    compareAtPrice: null,
  costPrice: 1400,
  videoUrl: null,
  sizeChartUrl: null,
  dropAt: null,
    stock: 5,
    category: "Tops",
    imageUrls: [],
    isActive: true,
    createdAt: now(),
  },
  {
    id: "p-shawl",
    options: [],
    tag: "new",
    shopId: "shop-zara",
    name: "Printed Shawl",
    description: "Lightweight printed shawl, perfect for everyday wear.",
    longDescription: null,
    price: 3800,
    compareAtPrice: null,
  costPrice: 2500,
  videoUrl: null,
  sizeChartUrl: null,
  dropAt: null,
    stock: 8,
    category: "Accessories",
    imageUrls: [],
    isActive: true,
    createdAt: now(),
  },
  {
    id: "p-heels",
    options: [],
    tag: null,
    shopId: "shop-zara",
    name: "Block Heels",
    description: "Comfortable block heels with cushioned sole.",
    longDescription: null,
    price: 5900,
    compareAtPrice: 6900,
  costPrice: 4100,
  videoUrl: null,
  sizeChartUrl: null,
  dropAt: null,
    stock: 0,
    category: "Shoes",
    imageUrls: [],
    isActive: true,
    createdAt: now(),
  },
];

// Demo orders (so the seller dashboard shows data in demo mode).
import type { Order } from "./types";

const seedOrders_: Order[] = [
  {
    id: "1041",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1041",
    shopId: "shop-zara",
    customerName: "Ayesha Khan",
    customerPhone: "923011112233",
    customerEmail: null,
    address: "House 12, Street 4, Gulshan-e-Iqbal",
    city: "Karachi",
    paymentMethod: "cod",
    subtotal: 4500,
    deliveryFee: 0, // free delivery (over Rs 3,000)
    total: 4500,
    status: "new",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1041-0", orderId: "1041", productId: "p-lawn", name: "Lawn Suit (3pc)", price: 4500, quantity: 1, variant: null },
    ],
  },
  {
    // A 45-day-old delivered order: makes the "Win them back" list show a real
    // example on the demo shop (buyers quiet for 30+ days).
    id: "1035",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1035",
    shopId: "shop-zara",
    customerName: "Sana Malik",
    customerPhone: "923219876543",
    customerEmail: null,
    address: "Flat 3B, Askari 11",
    city: "Lahore",
    paymentMethod: "cod",
    subtotal: 2200,
    deliveryFee: 250,
    total: 2450,
    status: "delivered",
    courier: "PostEx",
    trackingNumber: "PX-88231",
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: true,
    createdAt: new Date(Date.now() - 45 * 86400000).toISOString(),
    items: [
      { id: "1035-0", orderId: "1035", productId: "p-kurti", name: "Embroidered Kurti", price: 2200, quantity: 1, variant: "Size: M" },
    ],
  },
  {
    id: "1042",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1042",
    shopId: "shop-zara",
    customerName: "Bilal Ahmed",
    customerPhone: "923004445566",
    customerEmail: null,
    address: "Flat 7B, Clifton Block 2",
    city: "Karachi",
    paymentMethod: "online",
    subtotal: 2200,
    deliveryFee: 200,
    total: 2400,
    status: "confirmed",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1042-0", orderId: "1042", productId: "p-kurti", name: "Embroidered Kurti", price: 2200, quantity: 1, variant: null },
    ],
  },
  {
    id: "1043",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1043",
    shopId: "shop-hina",
    customerName: "Sana Malik",
    customerPhone: "923111234567",
    customerEmail: null,
    address: "Plot 9, DHA Phase 5",
    city: "Lahore",
    paymentMethod: "cod",
    subtotal: 3500,
    deliveryFee: 150,
    total: 3650,
    status: "delivered",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1043-0", orderId: "1043", productId: "h-abaya", name: "Black Abaya", price: 3500, quantity: 1, variant: null },
    ],
  },
  {
    id: "1044",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1044",
    shopId: "shop-hina",
    customerName: "Maria Tariq",
    customerPhone: "923119876543",
    customerEmail: null,
    address: "Street 2, Model Town",
    city: "Lahore",
    paymentMethod: "online",
    subtotal: 5200,
    deliveryFee: 0,
    total: 5200,
    status: "confirmed",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1044-0", orderId: "1044", productId: "h-set", name: "Hijab Set (3pc)", price: 5200, quantity: 1, variant: null },
    ],
  },
  {
    id: "1045",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1045",
    shopId: "shop-bilal",
    customerName: "Usman Raza",
    customerPhone: "923211112222",
    customerEmail: null,
    address: "Block 6, Gulistan-e-Johar",
    city: "Karachi",
    paymentMethod: "cod",
    subtotal: 8900,
    deliveryFee: 250,
    total: 9150,
    status: "new",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1045-0", orderId: "1045", productId: "b-buds", name: "Wireless Earbuds", price: 8900, quantity: 1, variant: null },
    ],
  },
  {
    id: "1050",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1050",
    shopId: "shop-zara",
    customerName: "Hira Sheikh",
    customerPhone: "923021110001",
    customerEmail: null,
    address: "House 10, Block 1, Gulshan",
    city: "Karachi",
    paymentMethod: "cod",
    subtotal: 4500,
    deliveryFee: 0,
    total: 4500,
    status: "delivered",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1050-0", orderId: "1050", productId: "p-lawn", name: "Lawn Suit (3pc)", price: 4500, quantity: 1, variant: null },
    ],
  },
  {
    id: "1051",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1051",
    shopId: "shop-zara",
    customerName: "Usman Tariq",
    customerPhone: "923022220002",
    customerEmail: null,
    address: "House 11, Block 2, Gulshan",
    city: "Karachi",
    paymentMethod: "cod",
    subtotal: 4500,
    deliveryFee: 0,
    total: 4500,
    status: "delivered",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1051-0", orderId: "1051", productId: "p-lawn", name: "Lawn Suit (3pc)", price: 4500, quantity: 1, variant: null },
    ],
  },
  {
    id: "1052",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1052",
    shopId: "shop-zara",
    customerName: "Fatima Noor",
    customerPhone: "923023330003",
    customerEmail: null,
    address: "House 12, Block 3, Gulshan",
    city: "Karachi",
    paymentMethod: "cod",
    subtotal: 4500,
    deliveryFee: 0,
    total: 4500,
    status: "delivered",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1052-0", orderId: "1052", productId: "p-lawn", name: "Lawn Suit (3pc)", price: 4500, quantity: 1, variant: null },
    ],
  },
  {
    id: "1053",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1053",
    shopId: "shop-zara",
    customerName: "Imran Ali",
    customerPhone: "923024440004",
    customerEmail: null,
    address: "House 13, Block 4, Gulshan",
    city: "Karachi",
    paymentMethod: "cod",
    subtotal: 4500,
    deliveryFee: 0,
    total: 4500,
    status: "delivered",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1053-0", orderId: "1053", productId: "p-lawn", name: "Lawn Suit (3pc)", price: 4500, quantity: 1, variant: null },
    ],
  },
  {
    id: "1054",
    discount: 0,
    discountCode: null,
    publicToken: "demo-token-1054",
    shopId: "shop-zara",
    customerName: "Sadia Iqbal",
    customerPhone: "923025550005",
    customerEmail: null,
    address: "House 14, Block 5, Gulshan",
    city: "Karachi",
    paymentMethod: "cod",
    subtotal: 4500,
    deliveryFee: 0,
    total: 4500,
    status: "delivered",
    courier: null,
    trackingNumber: null,
    paymentState: "none",
    gateway: null,
    gatewayRef: null,
    codCollected: false,
    createdAt: now(),
    items: [
      { id: "1054-0", orderId: "1054", productId: "p-lawn", name: "Lawn Suit (3pc)", price: 4500, quantity: 1, variant: null },
    ],
  },
];

import type { Category } from "./types";
const seedCategories: Category[] = [
  { id: "cat-dresses", shopId: "shop-zara", name: "Dresses", slug: "dresses", sortOrder: 0, createdAt: now() },
  { id: "cat-tops", shopId: "shop-zara", name: "Tops", slug: "tops", sortOrder: 1, createdAt: now() },
  { id: "cat-accessories", shopId: "shop-zara", name: "Accessories", slug: "accessories", sortOrder: 2, createdAt: now() },
  { id: "cat-shoes", shopId: "shop-zara", name: "Shoes", slug: "shoes", sortOrder: 3, createdAt: now() },
];

import type { Discount } from "./types";
const seedDiscounts: Discount[] = [
  { id: "disc-welcome", shopId: "shop-zara", code: "WELCOME10", type: "percent", value: 10, isActive: true, createdAt: now() },
  { id: "disc-save500", shopId: "shop-zara", code: "SAVE500", type: "fixed", value: 500, isActive: true, createdAt: now() },
];

import type { Review } from "./types";
const seedReviews: Review[] = [
  { id: "rev-1", shopId: "shop-zara", productId: "p-lawn", rating: 5, author: "Ayesha", comment: "Beautiful fabric and fast delivery!", photos: [], createdAt: now() },
  { id: "rev-2", shopId: "shop-zara", productId: "p-lawn", rating: 4, author: "Sana", comment: "Nice quality, runs a little big.", photos: [], createdAt: now() },
  { id: "rev-3", shopId: "shop-zara", productId: "p-kurti", rating: 5, author: "Hira", comment: "Loved it, will order again.", photos: [], createdAt: now() },
];

// Demo: mark Zara Boutique as a verified seller so the verified state is visible.
const _zaraVerified = seedShops.find((s) => s.id === "shop-zara");
if (_zaraVerified) {
  _zaraVerified.verificationStatus = "verified";
  _zaraVerified.cnicNumber = "4210112345678";
  _zaraVerified.cnicImageUrl = null;
  _zaraVerified.payoutMethod = "easypaisa";
  _zaraVerified.payoutAccountName = "Zara Ahmed";
  _zaraVerified.payoutAccountNumber = "03001234567";
  _zaraVerified.verificationReviewedAt = new Date().toISOString();
  _zaraVerified.instagramUrl = "instagram.com/zaraboutique";
  _zaraVerified.facebookUrl = "facebook.com/zaraboutique";
}

// Demo: show a few different storefront templates across the sample shops.
const _templates: Record<string, string> = {
  "shop-zara": "magazine",
  "shop-hina": "bold",
  "shop-bilal": "playful",
  "shop-old": "minimal",
};
for (const _s of seedShops) {
  if (_templates[_s.id]) _s.template = _templates[_s.id];
}

// Demo: extra products on Zara so the grid + "Load more" is visible.
const _zBase = seedProducts.find((p) => p.id === "p-lawn");
if (_zBase) {
  const _names = [
    "Embroidered frock", "Cotton co-ord set", "Chiffon dupatta", "Printed kurta",
    "Velvet shawl", "Khaddar shirt", "Linen trousers", "Net maxi dress",
    "Denim jacket", "Strappy sandals", "Silk scarf", "Pearl earrings",
  ];
  const _cats = ["Dresses", "Tops", "Accessories", "Shoes"];
  _names.forEach((name, i) => {
    seedProducts.push({
      ..._zBase,
      id: "p-demo-" + i,
      name,
      description: "Demo product, added to show the storefront grid and the Load more button.",
      longDescription: null,
      price: 1500 + i * 350,
      compareAtPrice: i % 3 === 0 ? 1500 + i * 350 + 700 : null,
  costPrice: null,
  videoUrl: null,
  sizeChartUrl: null,
  dropAt: null,
      stock: i % 5 === 0 ? 0 : 8 + i,
      tag: i === 0 ? "new" : null,
      category: _cats[i % 4],
      imageUrls: [],
      createdAt: new Date().toISOString(),
    });
  });
}

// ---------------------------------------------------------------------------
// Demo persistence across route bundles.
// In a production build each route can get its own copy of this module, which
// would mean a write in one route (adding a product, saving order tracking)
// isn't visible in another. Pinning the arrays to globalThis gives every
// bundle ONE shared instance, so demo mode behaves like a real datastore.
// (These arrays are only used when Supabase is not configured.)
// ---------------------------------------------------------------------------
type MockGlobal = {
  __wsbShops?: Shop[];
  __wsbProducts?: Product[];
  __wsbOrders?: Order[];
  __wsbCategories?: Category[];
  __wsbDiscounts?: Discount[];
  __wsbReviews?: Review[];
};
const mg = globalThis as unknown as MockGlobal;
mg.__wsbShops ??= seedShops;
mg.__wsbProducts ??= seedProducts;
mg.__wsbOrders ??= seedOrders_;
mg.__wsbCategories ??= seedCategories;
mg.__wsbDiscounts ??= seedDiscounts;
mg.__wsbReviews ??= seedReviews;

export const mockShops = mg.__wsbShops;
export const mockProducts = mg.__wsbProducts;
export const mockOrders = mg.__wsbOrders;
export const mockCategories = mg.__wsbCategories;
export const mockDiscounts = mg.__wsbDiscounts;
export const mockReviews = mg.__wsbReviews;
